name: Render Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --verbosity normal

    - name: Recreate SQLite database
      run: |
        rm -rf conways-game-of-life-api/Data/AppDbContext.db 
        dotnet ef database update --project conways-game-of-life-api --context AppDbContext

    - name: Publish to Render
      env:
        RENDER_EMAIL: ${{ secrets.RENDER_EMAIL }}
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        dotnet publish conways-game-of-life-api -c Release -o ./publish
        cd ./publish
        render deploy --config render.yaml --name your-app-name  # Adjust app name
